{% set name = "deepecho" %}
{% set version = "version = '0.1.5.dev0'" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.6,<3.9
    - numpy >=1.18.0,<2
    - pandas >=1.1,<1.1.5
    - pytorch >=1.4,<2
    - tqdm >=4.10,<5
  run:
    - python >=3.6,<3.9
    - numpy >=1.18.0,<2
    - pandas >=1.1,<1.1.5
    - pytorch >=1.4,<2
    - tqdm >=4.10,<5

about:
  home: "https://github.com/sdv-dev/DeepEcho"
  license: MIT
  license_family: MIT
  license_file:
  summary: "Mixed-type multivariate time series modeling with generative adversarial networks."
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - sdv-dev
