{% set name = "deepecho" %}
{% set version = "0.1.4.dev0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - numpy >=1.15.4,<2
    - pandas >=0.22,<2
    - pip
    - python
    - pytorch >=1,<2
    - tqdm >=4,<5
    - pytest-runner
  run:
    - numpy >=1.15.4,<2
    - pandas >=0.22,<2
    - python
    - pytorch >=1,<2
    - tqdm >=4,<5

about:
  home: "https://github.com/sdv-dev/DeepEcho"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "Mixed-type multivariate time series modeling with generative adversarial networks."
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - sdv-dev